<?php if ($this->tabs) echo $this->renderTabs($this->tabs) ?>
<?php echo $this->renderTools($this->tools) ?>
<?php echo $this->renderList($this->list) ?>
<script>
//<![CDATA[
function Modules_MyVPN_Confirm(url, type, text) {
    Jsw.messageBox.show({
        type: Jsw.messageBox.TYPE_YESNO,
        buttonTitles: {
            yes: '<?php echo $this->lmsg('buttonYes') ?>',
            no: '<?php echo $this->lmsg('buttonNo') ?>'
        },
        text: text,
        subtype: type,
        onYesClick: function () {
            Jsw.redirectPost(url);
        }
    });
}
//]]>
</script>
